version: '3'
services:
  server1:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - TEST_TYPE=1 # 0: ether sending test, 1: smart contract test
      - SMART_CONTRACT_OPTION=2 #0: lightweigth SC test, 1: David19-Smart contract test, 2: Kaytrust identity creation stress
      - DESIRED_RATE_TX=5
      - TEST_TIME_MINUTES=1 #0.0166666666666666666666666
      - RPC_URL=http://127.0.0.1:8550
      - NODE_ADDRESS=0xc2d2aef92e0828e4420e7cb94bda2acad537c6ca
      - MAX_GAS_PER_TX=4000000 #not necessary to change this unless you change your BLOCKPERIODSECONDS.
      - NUMBER_OF_CONTAINERS=1
      - STORE_DATA=TRUE
      #- NODE_TLS_REJECT_UNAUTHORIZED=0
    ############ SETTING FOR ETHER TESTING (IF REQUIRED) ##############      
      - AMOUNT_DATA_BYTES=0
    ############ SETTING FOR SMART CONTRACT TESTING ##############
      - SMART_CONTRACT_ADDRESS=0xCf2ee94F1f992Ac46e860E2c159cB4409a626908 #to avoid deploying a contract again
    network_mode: host #using localhost instead of isolated network
  
  # server2:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./server
  #   volumes:
  #     - /app/node_modules
  #     - ./server:/app
  #   environment:
  #     - TEST_TYPE=1 # 0: ether sending test, 1: smart contract test
  #     - SMART_CONTRACT_OPTION=2 #0: lightweigth SC test, 1: David19-Smart contract test, 2: Kaytrust identity creation stress
  #     - DESIRED_RATE_TX=5
  #     - TEST_TIME_MINUTES=1 #0.0166666666666666666666666
  #     - RPC_URL=http://127.0.0.1:8550
  #     - MAX_GAS_PER_TX=4000000 #not necessary to change this unless you change your BLOCKPERIODSECONDS.
  #     - NUMBER_OF_CONTAINERS=4
  #     - STORE_DATA=FALSE
  #     #- NODE_TLS_REJECT_UNAUTHORIZED=0
  #   ############ SETTING FOR ETHER TESTING (IF REQUIRED) ##############      
  #     - AMOUNT_DATA_BYTES=0
  #   ############ SETTING FOR SMART CONTRACT TESTING ##############
  #     - SMART_CONTRACT_ADDRESS=0xCf2ee94F1f992Ac46e860E2c159cB4409a626908 #to avoid deploying a contract again
  #   network_mode: host #using localhost instead of isolated network

  # server3:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./server
  #   volumes:
  #     - /app/node_modules
  #     - ./server:/app
  #   environment:
  #     - TEST_TYPE=1 # 0: ether sending test, 1: smart contract test
  #     - SMART_CONTRACT_OPTION=2 #0: lightweigth SC test, 1: David19-Smart contract test, 2: Kaytrust identity creation stress
  #     - DESIRED_RATE_TX=5
  #     - TEST_TIME_MINUTES=1 #0.0166666666666666666666666
  #     - RPC_URL=http://127.0.0.1:8550
  #     - MAX_GAS_PER_TX=4000000 #not necessary to change this unless you change your BLOCKPERIODSECONDS.
  #     - NUMBER_OF_CONTAINERS=4
  #     - STORE_DATA=FALSE
  #     #- NODE_TLS_REJECT_UNAUTHORIZED=0
  #   ############ SETTING FOR ETHER TESTING (IF REQUIRED) ##############      
  #     - AMOUNT_DATA_BYTES=0
  #   ############ SETTING FOR SMART CONTRACT TESTING ##############
  #     - SMART_CONTRACT_ADDRESS=0xCf2ee94F1f992Ac46e860E2c159cB4409a626908 #to avoid deploying a contract again
  #   network_mode: host #using localhost instead of isolated network    

  # server4:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./server
  #   volumes:
  #     - /app/node_modules
  #     - ./server:/app
  #   environment:
  #     - TEST_TYPE=1 # 0: ether sending test, 1: smart contract test
  #     - SMART_CONTRACT_OPTION=2 #0: lightweigth SC test, 1: David19-Smart contract test, 2: Kaytrust identity creation stress
  #     - DESIRED_RATE_TX=5
  #     - TEST_TIME_MINUTES=1 #0.0166666666666666666666666
  #     - RPC_URL=http://127.0.0.1:8550
  #     - MAX_GAS_PER_TX=4000000 #not necessary to change this unless you change your BLOCKPERIODSECONDS.
  #     - NUMBER_OF_CONTAINERS=4
  #     - STORE_DATA=FALSE
  #     #- NODE_TLS_REJECT_UNAUTHORIZED=0
  #   ############ SETTING FOR ETHER TESTING (IF REQUIRED) ##############      
  #     - AMOUNT_DATA_BYTES=0
  #   ############ SETTING FOR SMART CONTRACT TESTING ##############
  #     - SMART_CONTRACT_ADDRESS=0xCf2ee94F1f992Ac46e860E2c159cB4409a626908 #to avoid deploying a contract again
  #   network_mode: host #using localhost instead of isolated network